name: WeatherTool
version: '${project.version}'
main: dk.noxitech.weathertool.main
authors: [ notfoundofficial, NoXi ]
api-version: 1.21
softdepend:
  - LuckPerms
commands:
  weather:
    description: Use the Weather Tool.
    usage: /<command>